cluster:
  apiServer: "https://kubernetes.example.com:6443"
  caPath: "/path/to/ca.crt"  # Optional
  insecure: false           # Optional
  qps: 100                  # Higher QPS to avoid throttling
  burst: 200                # Higher burst to avoid throttling

users:
  - username: "user1"
    token: "token1"
    concurrency: 10
  - username: "user2"
    token: "token2"
    concurrency: 5